version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80
    environment:
      - EUREKA_SERVER=http://discovery-server:8090/eureka

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service

  discovery-server:
    image: eureka
    ports:
      - 8090:8090